"""add_employee_onboardings_and_onboarding_documents

Revision ID: 01c8240cd769
Revises: aebc600ae30d
Create Date: 2026-05-07 12:53:47.008660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01c8240cd769'
down_revision: Union[str, None] = 'aebc600ae30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_onboardings',
    sa.Column('auto_employee_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('marital_status', sa.String(length=30), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('profile_picture_key', sa.String(length=500), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('job_code', sa.String(length=50), nullable=True),
    sa.Column('sub_department', sa.String(length=100), nullable=True),
    sa.Column('grade_band', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('work_location_id', sa.UUID(), nullable=True),
    sa.Column('employment_type', sa.String(length=30), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('probation_end_date', sa.Date(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('reporting_manager_id', sa.UUID(), nullable=True),
    sa.Column('buddy_id', sa.UUID(), nullable=True),
    sa.Column('annual_ctc', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('ctc_effective_from', sa.Date(), nullable=True),
    sa.Column('salary_structure_id', sa.UUID(), nullable=True),
    sa.Column('ctc_breakdown', sa.JSON(), nullable=True),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('bank_branch', sa.String(length=150), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('leave_plan', sa.String(length=100), nullable=True),
    sa.Column('holiday_calendar', sa.String(length=100), nullable=True),
    sa.Column('leave_allocations', sa.JSON(), nullable=True),
    sa.Column('cost_centre', sa.String(length=100), nullable=True),
    sa.Column('business_unit', sa.String(length=100), nullable=True),
    sa.Column('legal_entity', sa.String(length=100), nullable=True),
    sa.Column('workspace_team', sa.String(length=100), nullable=True),
    sa.Column('work_email', sa.String(length=255), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activated_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['buddy_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_location_id'], ['work_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_onboardings_auto_employee_code'), 'employee_onboardings', ['auto_employee_code'], unique=True)
    op.create_index(op.f('ix_employee_onboardings_created_by'), 'employee_onboardings', ['created_by'], unique=False)
    op.create_index(op.f('ix_employee_onboardings_id'), 'employee_onboardings', ['id'], unique=False)
    op.create_table('onboarding_documents',
    sa.Column('onboarding_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_id'], ['employee_onboardings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_documents_id'), 'onboarding_documents', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_documents_onboarding_id'), 'onboarding_documents', ['onboarding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_documents_onboarding_id'), table_name='onboarding_documents')
    op.drop_index(op.f('ix_onboarding_documents_id'), table_name='onboarding_documents')
    op.drop_table('onboarding_documents')
    op.drop_index(op.f('ix_employee_onboardings_id'), table_name='employee_onboardings')
    op.drop_index(op.f('ix_employee_onboardings_created_by'), table_name='employee_onboardings')
    op.drop_index(op.f('ix_employee_onboardings_auto_employee_code'), table_name='employee_onboardings')
    op.drop_table('employee_onboardings')
    # ### end Alembic commands ###
