"""initial schema

Revision ID: aebc600ae30d
Revises: 
Create Date: 2026-05-06 08:42:50.358368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aebc600ae30d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_locations',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_work_locations_deleted_at'), 'work_locations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_work_locations_id'), 'work_locations', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('head_employee_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_deleted_at'), 'departments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('designations',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designations_deleted_at'), 'designations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_designations_department_id'), 'designations', ['department_id'], unique=False)
    op.create_index(op.f('ix_designations_id'), 'designations', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('employment_type', sa.String(length=30), nullable=False),
    sa.Column('work_location_type', sa.String(length=30), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('date_of_leaving', sa.Date(), nullable=True),
    sa.Column('probation_end_date', sa.Date(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('designation_id', sa.UUID(), nullable=True),
    sa.Column('work_location_id', sa.UUID(), nullable=True),
    sa.Column('reporting_manager_id', sa.UUID(), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('aadhar_number', sa.String(length=20), nullable=True),
    sa.Column('uan_number', sa.String(length=20), nullable=True),
    sa.Column('esic_number', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('current_ctc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_location_id'], ['work_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_deleted_at'), 'employees', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_designation_id'), 'employees', ['designation_id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_reporting_manager_id'), 'employees', ['reporting_manager_id'], unique=False)
    # Add deferred circular FK: departments.head_employee_id -> employees
    op.create_foreign_key('fk_departments_head_employee_id', 'departments', 'employees', ['head_employee_id'], ['id'], ondelete='SET NULL')
    op.create_table('helpdesk_categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_helpdesk_categories_deleted_at'), 'helpdesk_categories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_helpdesk_categories_id'), 'helpdesk_categories', ['id'], unique=False)
    op.create_table('leave_policies',
    sa.Column('leave_type', sa.String(length=10), nullable=False),
    sa.Column('annual_quota', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('carry_forward_limit', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('max_consecutive_days', sa.Integer(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('min_days_notice', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leave_type')
    )
    op.create_index(op.f('ix_leave_policies_deleted_at'), 'leave_policies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_leave_policies_id'), 'leave_policies', ['id'], unique=False)
    op.create_table('organisations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('cin', sa.String(length=30), nullable=True),
    sa.Column('pf_registration_number', sa.String(length=50), nullable=True),
    sa.Column('esi_registration_number', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('logo_key', sa.String(length=500), nullable=True),
    sa.Column('financial_year_start_month', sa.Integer(), nullable=False),
    sa.Column('payroll_cycle_day', sa.Integer(), nullable=False),
    sa.Column('is_pf_applicable', sa.Boolean(), nullable=False),
    sa.Column('is_esi_applicable', sa.Boolean(), nullable=False),
    sa.Column('is_professional_tax_applicable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    op.create_table('permission_policies',
    sa.Column('max_hours_per_day', sa.Float(), nullable=False),
    sa.Column('max_hours_per_month', sa.Float(), nullable=False),
    sa.Column('excess_action', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_policies_id'), 'permission_policies', ['id'], unique=False)
    op.create_table('salary_components',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('component_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('calc_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('is_pf_applicable', sa.Boolean(), nullable=False),
    sa.Column('is_esi_applicable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_salary_components_deleted_at'), 'salary_components', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_salary_components_id'), 'salary_components', ['id'], unique=False)
    op.create_table('salary_structures',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_salary_structures_deleted_at'), 'salary_structures', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_salary_structures_id'), 'salary_structures', ['id'], unique=False)
    op.create_table('shift_schedules',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_schedules_deleted_at'), 'shift_schedules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_shift_schedules_id'), 'shift_schedules', ['id'], unique=False)
    op.create_table('announcements',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.String(length=30), nullable=False),
    sa.Column('target_department_id', sa.UUID(), nullable=True),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['published_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_deleted_at'), 'announcements', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('clock_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clock_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clock_in_method', sa.String(length=20), nullable=True),
    sa.Column('clock_out_method', sa.String(length=20), nullable=True),
    sa.Column('work_hours', sa.Float(), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('is_early_out', sa.Boolean(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_attendance_date'), 'attendance_records', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('employee_documents',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_documents_employee_id'), 'employee_documents', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_documents_id'), 'employee_documents', ['id'], unique=False)
    op.create_table('employee_salaries',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=True),
    sa.Column('ctc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('basic', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=False),
    sa.Column('tax_regime', sa.String(length=10), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_id'], ['salary_structures.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_salaries_deleted_at'), 'employee_salaries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employee_salaries_employee_id'), 'employee_salaries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_salaries_id'), 'employee_salaries', ['id'], unique=False)
    op.create_table('employee_shift_assignments',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_shift_assignments_employee_id'), 'employee_shift_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_id'), 'employee_shift_assignments', ['id'], unique=False)
    op.create_table('fnf_settlements',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('last_working_day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('notice_shortfall_days', sa.Integer(), nullable=False),
    sa.Column('notice_recovery_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('leave_encashment_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('leave_encashment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gratuity_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_payable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fnf_settlements_deleted_at'), 'fnf_settlements', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fnf_settlements_employee_id'), 'fnf_settlements', ['employee_id'], unique=True)
    op.create_index(op.f('ix_fnf_settlements_id'), 'fnf_settlements', ['id'], unique=False)
    op.create_table('helpdesk_tickets',
    sa.Column('ticket_number', sa.String(length=30), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['helpdesk_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helpdesk_tickets_deleted_at'), 'helpdesk_tickets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_helpdesk_tickets_employee_id'), 'helpdesk_tickets', ['employee_id'], unique=False)
    op.create_index(op.f('ix_helpdesk_tickets_id'), 'helpdesk_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_helpdesk_tickets_ticket_number'), 'helpdesk_tickets', ['ticket_number'], unique=True)
    op.create_table('holidays',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('holiday_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('work_location_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['work_location_id'], ['work_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_deleted_at'), 'holidays', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_holidays_holiday_date'), 'holidays', ['holiday_date'], unique=False)
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.create_index(op.f('ix_holidays_year'), 'holidays', ['year'], unique=False)
    op.create_table('leave_balances',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entitled', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('taken', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('carried_forward', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('encashed', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('lop_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_balances_employee_id'), 'leave_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_id'), 'leave_balances', ['id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=10), nullable=False),
    sa.Column('duration_type', sa.String(length=20), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('days_count', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_deleted_at'), 'leave_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('payroll_adjustments',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_adjustments_deleted_at'), 'payroll_adjustments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_employee_id'), 'payroll_adjustments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_id'), 'payroll_adjustments', ['id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_employees', sa.Integer(), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_runs_deleted_at'), 'payroll_runs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_payroll_runs_id'), 'payroll_runs', ['id'], unique=False)
    op.create_table('permission_requests',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('permission_date', sa.Date(), nullable=False),
    sa.Column('permission_type', sa.String(length=20), nullable=False),
    sa.Column('from_time', sa.Time(), nullable=False),
    sa.Column('to_time', sa.Time(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_requests_deleted_at'), 'permission_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_permission_requests_employee_id'), 'permission_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_permission_requests_id'), 'permission_requests', ['id'], unique=False)
    op.create_table('salary_revisions',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('revision_type', sa.String(length=20), nullable=False),
    sa.Column('old_ctc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_ctc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hike_percentage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('letter_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_revisions_deleted_at'), 'salary_revisions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_salary_revisions_employee_id'), 'salary_revisions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_salary_revisions_id'), 'salary_revisions', ['id'], unique=False)
    op.create_table('salary_structure_components',
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('calc_type_override', sa.String(length=20), nullable=True),
    sa.Column('value_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['salary_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_id'], ['salary_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_structure_components_id'), 'salary_structure_components', ['id'], unique=False)
    op.create_index(op.f('ix_salary_structure_components_structure_id'), 'salary_structure_components', ['structure_id'], unique=False)
    op.create_table('tds_declarations',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('tax_regime', sa.String(length=10), nullable=False),
    sa.Column('declared_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('declaration_data', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_declarations_deleted_at'), 'tds_declarations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tds_declarations_employee_id'), 'tds_declarations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_tds_declarations_id'), 'tds_declarations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('activation_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('attendance_regularisations',
    sa.Column('attendance_record_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('requested_clock_in', sa.Time(), nullable=True),
    sa.Column('requested_clock_out', sa.Time(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_regularisations_attendance_record_id'), 'attendance_regularisations', ['attendance_record_id'], unique=False)
    op.create_index(op.f('ix_attendance_regularisations_deleted_at'), 'attendance_regularisations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_attendance_regularisations_employee_id'), 'attendance_regularisations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_regularisations_id'), 'attendance_regularisations', ['id'], unique=False)
    op.create_table('helpdesk_comments',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['helpdesk_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helpdesk_comments_id'), 'helpdesk_comments', ['id'], unique=False)
    op.create_index(op.f('ix_helpdesk_comments_ticket_id'), 'helpdesk_comments', ['ticket_id'], unique=False)
    op.create_table('payslips',
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('paid_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('lop_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_employee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pf_employer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('esi_employee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('esi_employer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('pdf_key', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('component_breakdown', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_id'), 'payslips', ['id'], unique=False)
    op.create_index(op.f('ix_payslips_payroll_run_id'), 'payslips', ['payroll_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payslips_payroll_run_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_helpdesk_comments_ticket_id'), table_name='helpdesk_comments')
    op.drop_index(op.f('ix_helpdesk_comments_id'), table_name='helpdesk_comments')
    op.drop_table('helpdesk_comments')
    op.drop_index(op.f('ix_attendance_regularisations_id'), table_name='attendance_regularisations')
    op.drop_index(op.f('ix_attendance_regularisations_employee_id'), table_name='attendance_regularisations')
    op.drop_index(op.f('ix_attendance_regularisations_deleted_at'), table_name='attendance_regularisations')
    op.drop_index(op.f('ix_attendance_regularisations_attendance_record_id'), table_name='attendance_regularisations')
    op.drop_table('attendance_regularisations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tds_declarations_id'), table_name='tds_declarations')
    op.drop_index(op.f('ix_tds_declarations_employee_id'), table_name='tds_declarations')
    op.drop_index(op.f('ix_tds_declarations_deleted_at'), table_name='tds_declarations')
    op.drop_table('tds_declarations')
    op.drop_index(op.f('ix_salary_structure_components_structure_id'), table_name='salary_structure_components')
    op.drop_index(op.f('ix_salary_structure_components_id'), table_name='salary_structure_components')
    op.drop_table('salary_structure_components')
    op.drop_index(op.f('ix_salary_revisions_id'), table_name='salary_revisions')
    op.drop_index(op.f('ix_salary_revisions_employee_id'), table_name='salary_revisions')
    op.drop_index(op.f('ix_salary_revisions_deleted_at'), table_name='salary_revisions')
    op.drop_table('salary_revisions')
    op.drop_index(op.f('ix_permission_requests_id'), table_name='permission_requests')
    op.drop_index(op.f('ix_permission_requests_employee_id'), table_name='permission_requests')
    op.drop_index(op.f('ix_permission_requests_deleted_at'), table_name='permission_requests')
    op.drop_table('permission_requests')
    op.drop_index(op.f('ix_payroll_runs_id'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_deleted_at'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_payroll_adjustments_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_employee_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_deleted_at'), table_name='payroll_adjustments')
    op.drop_table('payroll_adjustments')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_deleted_at'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_leave_balances_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_employee_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_holidays_year'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_holiday_date'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_deleted_at'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_helpdesk_tickets_ticket_number'), table_name='helpdesk_tickets')
    op.drop_index(op.f('ix_helpdesk_tickets_id'), table_name='helpdesk_tickets')
    op.drop_index(op.f('ix_helpdesk_tickets_employee_id'), table_name='helpdesk_tickets')
    op.drop_index(op.f('ix_helpdesk_tickets_deleted_at'), table_name='helpdesk_tickets')
    op.drop_table('helpdesk_tickets')
    op.drop_index(op.f('ix_fnf_settlements_id'), table_name='fnf_settlements')
    op.drop_index(op.f('ix_fnf_settlements_employee_id'), table_name='fnf_settlements')
    op.drop_index(op.f('ix_fnf_settlements_deleted_at'), table_name='fnf_settlements')
    op.drop_table('fnf_settlements')
    op.drop_index(op.f('ix_employee_shift_assignments_id'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_employee_id'), table_name='employee_shift_assignments')
    op.drop_table('employee_shift_assignments')
    op.drop_index(op.f('ix_employee_salaries_id'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_employee_id'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_deleted_at'), table_name='employee_salaries')
    op.drop_table('employee_salaries')
    op.drop_index(op.f('ix_employee_documents_id'), table_name='employee_documents')
    op.drop_index(op.f('ix_employee_documents_employee_id'), table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_deleted_at'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_work_locations_id'), table_name='work_locations')
    op.drop_index(op.f('ix_work_locations_deleted_at'), table_name='work_locations')
    op.drop_table('work_locations')
    op.drop_index(op.f('ix_shift_schedules_id'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_deleted_at'), table_name='shift_schedules')
    op.drop_table('shift_schedules')
    op.drop_index(op.f('ix_salary_structures_id'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_deleted_at'), table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_index(op.f('ix_salary_components_id'), table_name='salary_components')
    op.drop_index(op.f('ix_salary_components_deleted_at'), table_name='salary_components')
    op.drop_table('salary_components')
    op.drop_index(op.f('ix_permission_policies_id'), table_name='permission_policies')
    op.drop_table('permission_policies')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_leave_policies_id'), table_name='leave_policies')
    op.drop_index(op.f('ix_leave_policies_deleted_at'), table_name='leave_policies')
    op.drop_table('leave_policies')
    op.drop_index(op.f('ix_helpdesk_categories_id'), table_name='helpdesk_categories')
    op.drop_index(op.f('ix_helpdesk_categories_deleted_at'), table_name='helpdesk_categories')
    op.drop_table('helpdesk_categories')
    op.drop_constraint('fk_departments_head_employee_id', 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_employees_reporting_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_designation_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_deleted_at'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_designations_id'), table_name='designations')
    op.drop_index(op.f('ix_designations_department_id'), table_name='designations')
    op.drop_index(op.f('ix_designations_deleted_at'), table_name='designations')
    op.drop_table('designations')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_deleted_at'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
