"""add_lookup_tables

Revision ID: ddf3068832ef
Revises: 01c8240cd769
Create Date: 2026-05-07 11:34:19.097973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ddf3068832ef'
down_revision: Union[str, None] = '01c8240cd769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_groups',
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_blood_groups_deleted_at'), 'blood_groups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_blood_groups_id'), 'blood_groups', ['id'], unique=False)
    op.create_table('marital_statuses',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_marital_statuses_deleted_at'), 'marital_statuses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_marital_statuses_id'), 'marital_statuses', ['id'], unique=False)
    op.create_table('nationalities',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_nationalities_deleted_at'), 'nationalities', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_nationalities_id'), 'nationalities', ['id'], unique=False)
    op.create_table('relationships',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_relationships_deleted_at'), 'relationships', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_relationships_id'), 'relationships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_deleted_at'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_nationalities_id'), table_name='nationalities')
    op.drop_index(op.f('ix_nationalities_deleted_at'), table_name='nationalities')
    op.drop_table('nationalities')
    op.drop_index(op.f('ix_marital_statuses_id'), table_name='marital_statuses')
    op.drop_index(op.f('ix_marital_statuses_deleted_at'), table_name='marital_statuses')
    op.drop_table('marital_statuses')
    op.drop_index(op.f('ix_blood_groups_id'), table_name='blood_groups')
    op.drop_index(op.f('ix_blood_groups_deleted_at'), table_name='blood_groups')
    op.drop_table('blood_groups')
    # ### end Alembic commands ###
